---
name: "🐛 Bug Report"
description: Create a report to help us improve
labels: [ bug ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: |
        Please include full errors, uncaught exceptions, screenshots, and relevant logs.
        Logs can be found under '/Users/<user>/.jfrog-docker-desktop-extension/logs'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Provide steps to reproduce the behavior.
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        What did you expect to happen?
    validations:
      required: false

  - type: input
    id: docker-version
    attributes:
      label: Docker Client and Desktop info
      description: using 'docker version' command on your CLI
    validations:
      required: true
      
  - type: input
    id: jfrog-docker-version
    attributes:
      label: JFrog Docker Desktop Extension version
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating system type, architecture and version
    validations:
      required: true
      
  - type: input
    id: cli-version
    attributes:
      label: JFrog CLI version
    validations:
      required: false

  - type: input
    id: xr-version
    attributes:
      label: JFrog Xray version
    validations:
      required: false
