name: Lint

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v3

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  
            - name: Yarn Install
              working-directory: './client'            
              run: yarn build

            - name: Yarn Lint
              working-directory: './client'            
              run: yarn lint
